const language = {
    "af-ZA": "Afrikaans",
"am-ET": "Amharic",
"ar-SA": "Arabic (Saudi Arabia)",
"ar-AE": "Arabic (UAE)",
"ar-BH": "Arabic (Bahrain)",
"ar-DZ": "Arabic (Algeria)",
"ar-EG": "Arabic (Egypt)",
"ar-IQ": "Arabic (Iraq)",
"ar-JO": "Arabic (Jordan)",
"ar-KW": "Arabic (Kuwait)",
"ar-LB": "Arabic (Lebanon)",
"ar-MA": "Arabic (Morocco)",
"ar-OM": "Arabic (Oman)",
"ar-QA": "Arabic (Qatar)",
"ar-SY": "Arabic (Syria)",
"ar-TN": "Arabic (Tunisia)",
"ar-YE": "Arabic (Yemen)",
"az-AZ": "Azerbaijani",
"be-BY": "Belarusian",
"bg-BG": "Bulgarian",
"bn-BD": "Bengali",
"bs-BA": "Bosnian",
"ca-ES": "Catalan",
"cs-CZ": "Czech",
"cy-GB": "Welsh",
"da-DK": "Danish",
"de-DE": "German (Germany)",
"de-AT": "German (Austria)",
"de-CH": "German (Switzerland)",
"el-GR": "Greek",
"en-GB": "English (UK)",
"en-US": "English (US)",
"en-AU": "English (Australia)",
"en-CA": "English (Canada)",
"en-IN": "English (India)",
"en-IE": "English (Ireland)",
"en-NZ": "English (New Zealand)",
"es-ES": "Spanish (Spain)",
"es-MX": "Spanish (Mexico)",
"es-AR": "Spanish (Argentina)",
"es-BO": "Spanish (Bolivia)",
"es-CL": "Spanish (Chile)",
"es-CO": "Spanish (Colombia)",
"es-CR": "Spanish (Costa Rica)",
"es-CU": "Spanish (Cuba)",
"es-DO": "Spanish (Dominican Republic)",
"es-EC": "Spanish (Ecuador)",
"es-GT": "Spanish (Guatemala)",
"es-HN": "Spanish (Honduras)",
"es-NI": "Spanish (Nicaragua)",
"es-PA": "Spanish (Panama)",
"es-PE": "Spanish (Peru)",
"es-PR": "Spanish (Puerto Rico)",
"es-PY": "Spanish (Paraguay)",
"es-SV": "Spanish (El Salvador)",
"es-UY": "Spanish (Uruguay)",
"es-VE": "Spanish (Venezuela)",
"et-EE": "Estonian",
"eu-ES": "Basque",
"fa-IR": "Persian",
"fi-FI": "Finnish",
"fr-FR": "French (France)",
"fr-CA": "French (Canada)",
"fr-BE": "French (Belgium)",
"fr-CH": "French (Switzerland)",
"fr-LU": "French (Luxembourg)",
"ga-IE": "Irish",
"gl-ES": "Galician",
"gu-IN": "Gujarati",
"he-IL": "Hebrew",
"hi-IN": "Hindi",
"hr-HR": "Croatian",
"hu-HU": "Hungarian",
"hy-AM": "Armenian",
"id-ID": "Indonesian",
"is-IS": "Icelandic",
"it-IT": "Italian",
"it-CH": "Italian (Switzerland)",
"ja-JP": "Japanese",
"ka-GE": "Georgian",
"kk-KZ": "Kazakh",
"km-KH": "Khmer",
"kn-IN": "Kannada",
"ko-KR": "Korean",
"lo-LA": "Lao",
"lt-LT": "Lithuanian",
"lv-LV": "Latvian",
"mk-MK": "Macedonian",
"ml-IN": "Malayalam",
"mn-MN": "Mongolian",
"mr-IN": "Marathi",
"ms-MY": "Malay",
"my-MM": "Burmese",
"ne-NP": "Nepali",
"nl-NL": "Dutch (Netherlands)",
"nl-BE": "Dutch (Belgium)",
"no-NO": "Norwegian",
"or-IN": "Odia",
"pa-IN": "Punjabi",
"pl-PL": "Polish",
"pt-BR": "Portuguese (Brazil)",
"pt-PT": "Portuguese (Portugal)",
"ro-RO": "Romanian",
"ru-RU": "Russian",
"si-LK": "Sinhala",
"sk-SK": "Slovak",
"sl-SI": "Slovenian",
"sq-AL": "Albanian",
"sr-RS": "Serbian",
"sv-SE": "Swedish",
"sw-KE": "Swahili",
"ta-IN": "Tamil",
"te-IN": "Telugu",
"th-TH": "Thai",
"tr-TR": "Turkish",
"uk-UA": "Ukrainian",
"ur-PK": "Urdu",
"uz-UZ": "Uzbek",
"vi-VN": "Vietnamese",
"xh-ZA": "Xhosa",
"yo-NG": "Yoruba",
"zh-CN": "Chinese (Simplified)",
"zh-TW": "Chinese (Traditional)",
"zu-ZA": "Zulu"

}